require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChefAccountsController do

  # This should return the minimal set of attributes required to create a valid
  # ChefAccount. As you add validations to ChefAccount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all chef_accounts as @chef_accounts" do
      chef_account = ChefAccount.create! valid_attributes
      get :index
      assigns(:chef_accounts).should eq([chef_account])
    end
  end

  describe "GET show" do
    it "assigns the requested chef_account as @chef_account" do
      chef_account = ChefAccount.create! valid_attributes
      get :show, :id => chef_account.id.to_s
      assigns(:chef_account).should eq(chef_account)
    end
  end

  describe "GET new" do
    it "assigns a new chef_account as @chef_account" do
      get :new
      assigns(:chef_account).should be_a_new(ChefAccount)
    end
  end

  describe "GET edit" do
    it "assigns the requested chef_account as @chef_account" do
      chef_account = ChefAccount.create! valid_attributes
      get :edit, :id => chef_account.id.to_s
      assigns(:chef_account).should eq(chef_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChefAccount" do
        expect {
          post :create, :chef_account => valid_attributes
        }.to change(ChefAccount, :count).by(1)
      end

      it "assigns a newly created chef_account as @chef_account" do
        post :create, :chef_account => valid_attributes
        assigns(:chef_account).should be_a(ChefAccount)
        assigns(:chef_account).should be_persisted
      end

      it "redirects to the created chef_account" do
        post :create, :chef_account => valid_attributes
        response.should redirect_to(ChefAccount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chef_account as @chef_account" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChefAccount.any_instance.stub(:save).and_return(false)
        post :create, :chef_account => {}
        assigns(:chef_account).should be_a_new(ChefAccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChefAccount.any_instance.stub(:save).and_return(false)
        post :create, :chef_account => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chef_account" do
        chef_account = ChefAccount.create! valid_attributes
        # Assuming there are no other chef_accounts in the database, this
        # specifies that the ChefAccount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChefAccount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => chef_account.id, :chef_account => {'these' => 'params'}
      end

      it "assigns the requested chef_account as @chef_account" do
        chef_account = ChefAccount.create! valid_attributes
        put :update, :id => chef_account.id, :chef_account => valid_attributes
        assigns(:chef_account).should eq(chef_account)
      end

      it "redirects to the chef_account" do
        chef_account = ChefAccount.create! valid_attributes
        put :update, :id => chef_account.id, :chef_account => valid_attributes
        response.should redirect_to(chef_account)
      end
    end

    describe "with invalid params" do
      it "assigns the chef_account as @chef_account" do
        chef_account = ChefAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChefAccount.any_instance.stub(:save).and_return(false)
        put :update, :id => chef_account.id.to_s, :chef_account => {}
        assigns(:chef_account).should eq(chef_account)
      end

      it "re-renders the 'edit' template" do
        chef_account = ChefAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChefAccount.any_instance.stub(:save).and_return(false)
        put :update, :id => chef_account.id.to_s, :chef_account => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chef_account" do
      chef_account = ChefAccount.create! valid_attributes
      expect {
        delete :destroy, :id => chef_account.id.to_s
      }.to change(ChefAccount, :count).by(-1)
    end

    it "redirects to the chef_accounts list" do
      chef_account = ChefAccount.create! valid_attributes
      delete :destroy, :id => chef_account.id.to_s
      response.should redirect_to(chef_accounts_url)
    end
  end

end
