require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomizationsController do

  # This should return the minimal set of attributes required to create a valid
  # Customization. As you add validations to Customization, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all customizations as @customizations" do
      customization = Customization.create! valid_attributes
      get :index
      assigns(:customizations).should eq([customization])
    end
  end

  describe "GET show" do
    it "assigns the requested customization as @customization" do
      customization = Customization.create! valid_attributes
      get :show, :id => customization.id
      assigns(:customization).should eq(customization)
    end
  end

  describe "GET new" do
    it "assigns a new customization as @customization" do
      get :new
      assigns(:customization).should be_a_new(Customization)
    end
  end

  describe "GET edit" do
    it "assigns the requested customization as @customization" do
      customization = Customization.create! valid_attributes
      get :edit, :id => customization.id
      assigns(:customization).should eq(customization)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Customization" do
        expect {
          post :create, :customization => valid_attributes
        }.to change(Customization, :count).by(1)
      end

      it "assigns a newly created customization as @customization" do
        post :create, :customization => valid_attributes
        assigns(:customization).should be_a(Customization)
        assigns(:customization).should be_persisted
      end

      it "redirects to the created customization" do
        post :create, :customization => valid_attributes
        response.should redirect_to(Customization.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customization as @customization" do
        # Trigger the behavior that occurs when invalid params are submitted
        Customization.any_instance.stub(:save).and_return(false)
        post :create, :customization => {}
        assigns(:customization).should be_a_new(Customization)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Customization.any_instance.stub(:save).and_return(false)
        post :create, :customization => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customization" do
        customization = Customization.create! valid_attributes
        # Assuming there are no other customizations in the database, this
        # specifies that the Customization created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Customization.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => customization.id, :customization => {'these' => 'params'}
      end

      it "assigns the requested customization as @customization" do
        customization = Customization.create! valid_attributes
        put :update, :id => customization.id, :customization => valid_attributes
        assigns(:customization).should eq(customization)
      end

      it "redirects to the customization" do
        customization = Customization.create! valid_attributes
        put :update, :id => customization.id, :customization => valid_attributes
        response.should redirect_to(customization)
      end
    end

    describe "with invalid params" do
      it "assigns the customization as @customization" do
        customization = Customization.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Customization.any_instance.stub(:save).and_return(false)
        put :update, :id => customization.id, :customization => {}
        assigns(:customization).should eq(customization)
      end

      it "re-renders the 'edit' template" do
        customization = Customization.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Customization.any_instance.stub(:save).and_return(false)
        put :update, :id => customization.id, :customization => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customization" do
      customization = Customization.create! valid_attributes
      expect {
        delete :destroy, :id => customization.id
      }.to change(Customization, :count).by(-1)
    end

    it "redirects to the customizations list" do
      customization = Customization.create! valid_attributes
      delete :destroy, :id => customization.id
      response.should redirect_to(customizations_url)
    end
  end

end
