require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatabasesController do

  # This should return the minimal set of attributes required to create a valid
  # Database. As you add validations to Database, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all databases as @databases" do
      database = Database.create! valid_attributes
      get :index
      assigns(:databases).should eq([database])
    end
  end

  describe "GET show" do
    it "assigns the requested database as @database" do
      database = Database.create! valid_attributes
      get :show, :id => database.id.to_s
      assigns(:database).should eq(database)
    end
  end

  describe "GET new" do
    it "assigns a new database as @database" do
      get :new
      assigns(:database).should be_a_new(Database)
    end
  end

  describe "GET edit" do
    it "assigns the requested database as @database" do
      database = Database.create! valid_attributes
      get :edit, :id => database.id.to_s
      assigns(:database).should eq(database)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Database" do
        expect {
          post :create, :database => valid_attributes
        }.to change(Database, :count).by(1)
      end

      it "assigns a newly created database as @database" do
        post :create, :database => valid_attributes
        assigns(:database).should be_a(Database)
        assigns(:database).should be_persisted
      end

      it "redirects to the created database" do
        post :create, :database => valid_attributes
        response.should redirect_to(Database.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved database as @database" do
        # Trigger the behavior that occurs when invalid params are submitted
        Database.any_instance.stub(:save).and_return(false)
        post :create, :database => {}
        assigns(:database).should be_a_new(Database)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Database.any_instance.stub(:save).and_return(false)
        post :create, :database => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested database" do
        database = Database.create! valid_attributes
        # Assuming there are no other databases in the database, this
        # specifies that the Database created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Database.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => database.id, :database => {'these' => 'params'}
      end

      it "assigns the requested database as @database" do
        database = Database.create! valid_attributes
        put :update, :id => database.id, :database => valid_attributes
        assigns(:database).should eq(database)
      end

      it "redirects to the database" do
        database = Database.create! valid_attributes
        put :update, :id => database.id, :database => valid_attributes
        response.should redirect_to(database)
      end
    end

    describe "with invalid params" do
      it "assigns the database as @database" do
        database = Database.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Database.any_instance.stub(:save).and_return(false)
        put :update, :id => database.id.to_s, :database => {}
        assigns(:database).should eq(database)
      end

      it "re-renders the 'edit' template" do
        database = Database.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Database.any_instance.stub(:save).and_return(false)
        put :update, :id => database.id.to_s, :database => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested database" do
      database = Database.create! valid_attributes
      expect {
        delete :destroy, :id => database.id.to_s
      }.to change(Database, :count).by(-1)
    end

    it "redirects to the databases list" do
      database = Database.create! valid_attributes
      delete :destroy, :id => database.id.to_s
      response.should redirect_to(databases_url)
    end
  end

end
